\
armorplus:ore_lava_crystal_stone armorplus:ore_lava_crystal_obsidian armorplus:ore_lava_crystal armorplus:ore_frost_crystal_stone armorplus:ore_frost_crystal_obsidian armorplus:ore_frost_crystal \
\
createnuclear:deepslate_lead_ore createnuclear:lead_ore createnuclear:deepslate_uranium_ore createnuclear:uranium_ore \
\
mofus_better_end_:meteorite_coal_ore mofus_better_end_:meteorite_iron_ore mofus_better_end_:meteorite_copper_ore mofus_better_end_:meteorite_gold_ore mofus_better_end_:meteorite_redstone_ore mofus_better_end_:meteorite_diamond_ore mofus_better_end_:meteorite_titanium_ore \
\
deeperdarker:gloomslate_coal_ore deeperdarker:sculk_stone_coal_ore \
